name: Release Docker Image

on:
  push:
    tags:
      - 'v*'            # e.g., v1.2.3
  release:
    types: [published]  # If you publish a GitHub Release

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Auto-generate tags/labels from git ref (tag) and default branch
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.IMAGE_NAME || 'DOCKERHUB_USERNAME/trivexer' }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag
            # Push "latest" when on default branch (main)
            type=raw,value=latest,enable={{is_default_branch}}
            # Always keep a SHA tag as a fallback
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.IMAGE_NAME || 'DOCKERHUB_USERNAME/trivexer' }}:buildcache
          cache-to: type=registry,ref=${{ secrets.IMAGE_NAME || 'DOCKERHUB_USERNAME/trivexer' }}:buildcache,mode=max